name: Lint

on:
  pull_request:
  push:
    branches:
      - main
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install pnpm package manager
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm run lint
